# Generated by Django 3.0.3 on 2022-03-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busApp', '0002_auto_20220228_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='ratings',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='', upload_to='photos'),
        ),
    ]
