# Generated by Django 3.0.3 on 2022-03-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busApp', '0004_auto_20220309_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
